### ISSUE TITLE
Arcus usability in .NET Core 3 projects

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus#53] opened 2020-02-27 23:19 UTC
**Is your feature request related to a problem? Please describe.**
.NET Core 3 uses another concept then .NET Core 2.2 when it comes to package-references, especially to references to Microsoft.Extensions.* and Microsoft.AspNetCore packages

Are the Arcus libs usable in both .NET Core 2.* and .NET Core 3.* projects ?
Shouldnt the package references of the Arcus libs be changed to something as is explained in [this](https://andrewlock.net/converting-a-netstandard-2-library-to-netcore-3/#libraries-that-depend-on-asp-net-core-nuget-packages) article ?

**Comment by tomkerkhove** [comment] 2020-03-04 09:44
Transferred to general Arcus repo as it impacts them all

**Comment by fgheysels** [comment] 2020-03-04 09:48
> Agreed, would be good to do this asap @stijnmoreels - Can you pick this up or not?

I'm giving it a go for Arcus.WebApi atm, but I'm running into some issues.

**Comment by stijnmoreels** [comment] 2020-03-04 10:56
So... not sure what the issue is here? Do I have to update something?

**Comment by tomkerkhove** [comment] 2020-03-04 11:01
We added netcoreapp3.0 but should be netstandard2.1 instead

**Comment by fgheysels** [comment] 2020-03-04 12:47
Should we keep it like it is now for projects that have dependencies on ASP.NET core, and change the targetframeworks to netstandard2.0 and netstandard2.1 for the projects that have no dependencies on ASP.NET Core libs ?

**Comment by tomkerkhove** [comment] 2020-03-04 13:53
We've had a look at other libraries in the community and we'll stick with what we have now similar to what Swashbuckle does - https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/cbdecd1063568478802ff01cb7328908ffeb6bf0

**Closed** 2020-03-04 13:53 UTC
